language: node_js
node_js:
  - "6"
# jdk:
#   - openjdk6
#   - openjdk7
#   - oraclejdk7
install:
  - mkdir /tmp/dynamodb
  - wget -O - https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb
before_script:
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
  # - npm install
cache:
  yarn: true